name: qwen25-2
project: photo_tagger
branch: main
port: 8000
description: Test models live - note that results are recoded for evaluation
image: vllm/vllm-openai:latest

auth:
  type: API

secrets:
  - huggingface-phototagger

compute_pools:
  - gpu-pool-inference-24gb

environment:
  PYTHONUNBUFFERED: 1

replicas:
  min: 1
  max: 1

commands:
  - vllm serve Qwen/Qwen2.5-VL-3B-Instruct

resources:
  cpu: 2
  memory: "28Gi"
  disk: 10000
  gpu: 1

