name: model-tester9
project: photo_tagger
branch: main
port: 8000
description: Test models live - note that results are recoded for evaluation
secrets:
  - togetherai
  - openai

compute_pools:
  - inference-testing

environment:
  PYTHONUNBUFFERED: 1

replicas:
  min: 1
  max: 1

commands:
  - streamlit run app.py --server.port 8000

models:
  - asset_id: o4-mini-2025-04-16
    asset_instance_id: a0
  - asset_id: gpt-4.1-2025-04-14
    asset_instance_id: b0
  - asset_id: llama-3.2-11B-Vision-Instruct-Turbo
    asset_instance_id: c0
  - asset_id: llama-3.2-90B-Vision-Instruct-Turbo
    asset_instance_id: d0

data:
  - asset_id: photos
    asset_instance_id: 098251011150_task_UpdatePhotos_argo_phototagger_user_villeouterbounds_co_updatepho_af35c61d-dbe1-4419-a0e0-e21decaa193a

