name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    name: "Test flows runs locally"
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    env:
      METAFLOW_DEFAULT_NAMESPACE: global
      MF_PYLINT: 0
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install openai==0.28.1 pytoml

      - name: Install and Configure Outerbounds
        run: |
          python -m pip install -U outerbounds
          outerbounds service-principal-configure \
          --name photo-tagger-deployer \
          --deployment-domain dev-yellow.outerbounds.xyz \
          --perimeter default \
          --github-actions

      - name: Run baseline flows (README)
        run: |
          python updatephotos.py --environment=fast-bakery run --allow-empty || true
          python promptmodels.py --environment=fast-bakery run
          python prepare_vlm_data.py --environment=fast-bakery run
          python finetune_vlm.py --environment=fast-bakery --no-pylint run
          python promptcustommodels.py --environment=fast-bakery run
          python evalsflow.py --environment=fast-bakery run