
provider = 'openai'
model = 'openai-o4-mini-2025-04-16'
kind = 'openai'
blobs = [["openai", "o4-mini-2025-04-16"]]
description = "Added on the CLI by [ville@outerbounds.co](#)"

[tags]
authentication = "https://ui.dev-yellow.outerbounds.xyz/dashboard/integrations/p/default/openai"
external_endpoint_url = "https://platform.openai.com/docs/models/o4-mini"
