
provider = 'togetherai'
model = 'togetherai-llama-3-2-11b-vision-instruct-turbo'
kind = 'meta'
blobs = [["togetherai", "meta-llama/Llama-3.2-11B-Vision-Instruct-Turbo"]]
description = "Added on the CLI by [ville@outerbounds.co](#)"

[tags]
authentication = "https://ui.dev-yellow.outerbounds.xyz/dashboard/integrations/p/default/togetherai"
external_endpoint_url = "https://api.together.ai/models/meta-llama/Llama-3.2-90B-Vision-Instruct-Turbo"
